import { GoogleGenAI } from "@google/genai";
import { Sport } from "../models/Sport";
import { SportPathway, SportPathwayDocument } from "../models/SportPathway";
import { Tournament } from "../models/Tournament";
import { Scholarship } from "../models/Scholarship";
import { University } from "../models/University";
import { realDataScraperService } from "./RealDataScraperService";
import { buildSafeSearchRegexSource } from "../../utils/regex";

const isDev = process.env.NODE_ENV !== "production";
const log = {
  info: (...args: unknown[]) => {
    if (isDev) console.log(...args);
  },
  warn: (...args: unknown[]) => console.warn(...args),
  error: (...args: unknown[]) => console.error(...args),
};

type CanonicalAttachResult = {
  pathway: SportPathwayDocument;
  warnings: string[];
  entitiesReady: boolean;
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function toSlug(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, "-");
}

function normalizeCity(city?: string): string {
  if (!city) return "";
  return city.trim().toLowerCase().replace(/\s+/g, "-");
}

/** Top Indian sports to pre-warm at startup so the first user always gets an instant response */
const POPULAR_SPORTS = [
  "Cricket",
  "Badminton",
  "Football",
  "Kabaddi",
  "Hockey",
  "Tennis",
  "Athletics",
  "Wrestling",
  "Shooting",
  "Swimming",
];

/** Days before a pathway is considered stale and eligible for background refresh */
const DEFAULT_STALE_DAYS = parseInt(process.env.PATHWAY_STALE_DAYS || "30", 10);

/**
 * Level 1 is always "Beginner" — every parent understands it regardless of sport.
 * Levels 2-5 are sport-specific (generated by the AI); these are only a safety-net
 * fallback in case the model omits a label for one of them.
 */
const LEVEL_LABEL_FALLBACKS = [
  "Beginner",
  "Intermediate",
  "Advanced",
  "National",
  "International",
];

// ─── Prompt ───────────────────────────────────────────────────────────────────

function buildPathwayMetaPrompt(sportName: string, state?: string): string {
  const stateContext = state
    ? `The family is based in the Indian state/UT of ${state.trim()}.`
    : "";

  return `You are an expert Indian sports development consultant advising an average Indian parent. Generate a detailed, highly actionable, and realistic sports development pathway metadata for their child in "${sportName}" within India.
${stateContext ? `\n${stateContext}` : ""}
WRITE IN SIMPLE LANGUAGE — this is the most important rule: Every field must read like you are speaking out loud to a parent who has never played sport and does not use advanced English. Use short sentences and everyday words. Never use a sport-federation acronym without immediately explaining it in plain words the first time, e.g. "AITA (the organisation that runs tennis in India)".

Return ONLY a valid JSON object (no markdown, no code fences) with this exact structure:
{
  "sportName": "Proper name of the sport",
  "category": "One of: Ball Sports | Racquet Sports | Combat Sports | Water Sports | Winter Sports | Team Sports | Individual Sports | Fitness | Other",
  "overview": "2-3 sentences explaining the sport's scope and future prospects in India to a parent, including why their child should pursue it.",
  "governingBodyNational": "Name of the national governing body in India (e.g. BCCI for Cricket, BAI for Badminton)",
  "equipment": [
    {
      "level": "e.g. this sport's own entry-level, intermediate, and elite tier names",
      "items": ["Item 1", "Item 2"],
      "estimatedCost": "e.g. ₹2,000 - ₹5,000"
    }
  ],
  "careers": [
    {
      "role": "e.g. Coach, Umpire, Sports Manager",
      "description": "Brief description of the career path",
      "demand": "e.g. High, Growing, Niche"
    }
  ]
}

Make all content specific to India's sports ecosystem. Do NOT include "tournaments", "scholarships", or "universities" arrays.`;
}

function buildLevelRangePrompt(
  sportName: string,
  state: string | undefined,
  levelNumbers: number[],
): string {
  const stateContext = state
    ? `The family is based in the Indian state/UT of ${state.trim()}.`
    : "";

  const levelObjects = levelNumbers.map(levelNumber => `{
  "level": ${levelNumber},
  "label": "Short, sport-specific plain-English name (or 'Beginner' if level 1)",
  "title": "Short, plain-English, sport-specific title for this tier",
  "description": "Simple, parent-friendly description of what to expect, how much time/money is involved, and how to get started in India.",
  "keyFocus": "Short phrase, e.g. 'Fun & Basic Skills'",
  "ageRange": "e.g. '5 – 14 years'",
  "competitions": "Key competitions at this level in India",
  "steps": ["Step 1", "Step 2", "Step 3", "Step 4"],
  "governingBody": "Relevant local/district/state/national/international body",
  "localResources": {
    "academies": ["Example academy 1"],
    "facilities": ["Example facility"],
    "governingBodies": ["Example federation branch"]
  },
  "benchmarks": {
    "description": "What a child at this level should physically and technically be able to do",
    "metrics": [{"metric": "specific skill", "target": "measurable target", "checkpointMonth": 6}]
  },
  "trialInfo": {
    "typicalMonths": "...",
    "precisionLevel": "exact or approximate",
    "registrationProcess": "...",
    "eligibilityAge": "...",
    "selectionCriteria": ["..."],
    "tips": ["..."]
  },
  "injuryRisks": {
    "commonInjuries": ["..."],
    "preventionTips": ["..."],
    "warningSignsToWatch": ["..."]
  },
  "talentSignals": {
    "physicalMarkers": ["..."],
    "cognitiveMarkers": ["..."],
    "behavioralMarkers": ["..."]
  },
  "mentalSkillsFocus": ["..."],
  "coachSelectionGuide": {
    "mustHave": ["..."],
    "niceToHave": ["..."],
    "redFlags": ["Warning sign 1", "Warning sign 2", "Warning sign 3 (MUST HAVE MINIMUM 3 RED FLAGS)"],
    "questionsToAsk": ["..."]
  },
  "governmentSchemes": [
    {
      "name": "...",
      "body": "...",
      "eligibility": "...",
      "benefit": "...",
      "howToApply": "...",
      "sourceURL": "...",
      "verifiedAsOf": "YYYY-MM-DD"
    }
  ],
  "academicIntegration": "Practical advice for parents on balancing school academics with sport at this specific level",
  "proactiveDocuments": ["Document to start collecting NOW that will be required at a higher level"]
}`).join(",\n");

  return `You are an expert Indian sports development consultant advising an average Indian parent. Generate detailed, highly actionable information for LEVELS ${levelNumbers.join(", ")} of a 5-level sports development pathway for their child in "${sportName}" within India.
${stateContext ? `\n${stateContext}` : ""}
WRITE IN SIMPLE LANGUAGE — this is the most important rule: Every field must read like you are speaking out loud to a parent who has never played sport and does not use advanced English. Use short sentences and everyday words. Never use a sport-federation acronym without immediately explaining it in plain words the first time.

LEVEL LABELS:
- If a level is 1, the "label" is ALWAYS exactly the word "Beginner".
- If a level is 2-5, the "label" MUST be a short (2-4 word) sport-specific, plain-English name for what that stage is actually called in "${sportName}". STRICTLY MAP the levels to the geographic scope of competition:
  - Level 2 MUST map to the District / Inter-City / Local competitive level.
  - Level 3 MUST map to the State / Provincial competitive level.
  - Level 4 MUST map to the National competitive level.
  - Level 5 MUST map to the International / Elite competitive level.
The "title" field is a slightly fuller version of the same idea.

BENCHMARKS REQUIREMENT: For any level whose ageRange or typical duration spans more than 12 months, the \`benchmarks.metrics\` array MUST contain at least 3 entries, each with a distinct \`checkpointMonth\` spaced across that level's full timeframe (e.g. months 6, 18, 36 for a 4-year level). For levels under 12 months, 1-2 checkpoints is acceptable.

Return ONLY a valid JSON array of objects (no markdown, no code fences) exactly matching this structure for the requested levels:
[
${levelObjects}
]

If a state was provided, you MUST populate the \`localResources\` object for levels 1, 2, and 3 with REAL, accurate names of academies, training facilities (e.g. SAI centres), and local federation branches located in or near that state. If none exist or you cannot be certain, leave the arrays empty.
`;
}

// ─── Service ──────────────────────────────────────────────────────────────────

export class PathwayService {
  private genAI: GoogleGenAI | null = null;

  /** Set of cacheKeys currently being refreshed — prevents duplicate Gemini calls */
  private refreshInProgressSet = new Set<string>();
  private sportValidationCache = new Map<string, boolean>();

  constructor() {
    const apiKey =
      process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || "";

    if (apiKey) {
      this.genAI = new GoogleGenAI({ apiKey });
    }
  }

  /**
   * Main entry point: get pathway from DB or generate + cache it.
   * Tournaments/scholarships/universities are loaded from the canonical
   * collections (not Gemini) via attachCanonicalEntities().
   * If the cached pathway is stale, a background refresh is triggered
   * (serve-stale-while-revalidating pattern).
   */
  async getOrGeneratePathway(
    sportName: string,
    state?: string,
  ): Promise<{
    pathway: SportPathwayDocument | null;
    source: "db" | "generated" | "not_a_sport";
    isStale?: boolean;
    entitiesReady?: boolean;
    message?: string;
    warnings?: string[];
  }> {
    let slug = toSlug(sportName);

    // ── 1. Validate with existing Sport collection FIRST ───────────────────
    const knownSport = await Sport.findOne({ slug });
    log.info(
      `[PathwayService] getOrGeneratePathway for ${sportName} - slug: ${slug}, knownSport:`,
      knownSport ? knownSport.name : "null",
    );

    const finalSportName = knownSport ? knownSport.name : sportName;
    slug = knownSport ? knownSport.slug : slug;

    // ── 2. Build composite cache key ───────────────────────────────────────
    const stateSlug = state ? toSlug(state) : "any";
    const cacheKey = `${slug}_${stateSlug}`;

    // ── 3. Check cache by cacheKey ─────────────────────────────────────────
    const existing = await SportPathway.findOne({ cacheKey });
    if (existing) {
      log.info(`[PathwayService] Cache hit for ${cacheKey}`);
      SportPathway.updateOne({ cacheKey }, { $inc: { lookupCount: 1 } }).exec();

      // ── Stale-while-revalidate: return cached, refresh in background ───
      // Expert-verified pathways are never auto-refreshed — that would
      // silently overwrite content an admin reviewed against expert input.
      const isStale = !existing.isVerified && this.isPathwayStale(existing);
      if (isStale && !this.refreshInProgressSet.has(cacheKey)) {
        log.info(
          `[PathwayService] Pathway ${cacheKey} is stale — triggering background refresh`,
        );
        this.refreshPathway(cacheKey).catch((err) =>
          log.error(
            `[PathwayService] Background refresh failed for ${cacheKey}:`,
            err,
          ),
        );
      }

      // Attach live canonical data (tournaments/scholarships/universities).
      // Non-blocking: if entities are missing the scraper fires in the background.
      const enriched = await this.attachCanonicalEntities(
        existing,
        slug,
        finalSportName,
        state,
      );
      return {
        pathway: enriched.pathway,
        source: "db",
        isStale,
        entitiesReady: enriched.entitiesReady,
        warnings: enriched.warnings,
      };
    }

    // ── 4. For unknown sports: validate + generate IN PARALLEL ─────────────
    //    For known sports: skip validation entirely (it's already confirmed).
    let generated: Awaited<ReturnType<typeof this.generatePathway>>;

    if (!knownSport) {
      log.info(
        `[PathwayService] Unknown sport — running validation: ${finalSportName}`,
      );
      const isValid = await this.validateSport(finalSportName);
      log.info(`[PathwayService] Validation: ${isValid}`);
      if (!isValid) {
        return {
          pathway: null,
          source: "not_a_sport",
          message: `"${finalSportName}" does not appear to be a recognised sport or athletic activity.`,
        };
      }
      generated = await this.generatePathway(finalSportName, state);
    } else {
      // ── 5. Known sport — generate directly (no validation round-trip) ────
      generated = await this.generatePathway(finalSportName, state);
    }

    if (!generated) {
      // Graceful fallback: if generation fails for a city/age variant,
      // serve any existing cached pathway for this sport slug.
      const fallbackDoc = await SportPathway.findOne({ sportSlug: slug }).sort({
        lookupCount: -1,
      });
      if (fallbackDoc) {
        log.warn(
          `[PathwayService] Generation failed for ${cacheKey} — serving fallback for ${slug}`,
        );
        const enriched = await this.attachCanonicalEntities(
          fallbackDoc,
          slug,
          finalSportName,
          state,
        );
        return {
          pathway: enriched.pathway,
          source: "db",
          isStale: true,
          entitiesReady: enriched.entitiesReady,
          warnings: [
            ...(enriched.warnings || []),
            "State-specific data is being generated. Showing general pathway for now.",
          ],
        };
      }
      return {
        pathway: null,
        source: "not_a_sport",
        message:
          "Could not generate pathway for this sport right now. Please try again in a moment.",
      };
    }

    // ── 6. Store in DB ─────────────────────────────────────────────────────
    if (knownSport) {
      generated.sportName = knownSport.name;
      if (knownSport.category && knownSport.category !== "Other") {
        generated.category = knownSport.category;
      }
    }

    const saved = await this.savePathway(slug, cacheKey, generated);

    // Attach canonical entities (non-blocking — scraper fires in background if needed)
    const enriched = await this.attachCanonicalEntities(
      saved,
      slug,
      finalSportName,
      state,
    );
    return {
      pathway: enriched.pathway,
      source: "generated",
      entitiesReady: enriched.entitiesReady,
      warnings: enriched.warnings,
    };
  }

  /**
   * Search for pathways by sport name prefix (for autocomplete).
   */
  async searchPathways(query: string): Promise<SportPathwayDocument[]> {
    // Escape + length-cap user input to prevent regex injection / ReDoS.
    const regex = new RegExp(buildSafeSearchRegexSource(query), "i");
    return SportPathway.find({
      $or: [{ sportName: regex }, { sportSlug: regex }],
    })
      .sort({ lookupCount: -1, sportName: 1 })
      .limit(10)
      .lean() as unknown as SportPathwayDocument[];
  }

  /**
   * Force-refresh the Gemini-generated skeleton of a pathway (levels/equipment/careers).
   * Tournaments/scholarships/universities continue to be served from canonical collections.
   * Safe to call fire-and-forget — duplicate calls for the same cacheKey are no-ops.
   */
  async refreshPathway(
    cacheKey: string,
    force: boolean = false,
  ): Promise<SportPathwayDocument | null> {
    if (this.refreshInProgressSet.has(cacheKey)) {
      log.info(
        `[PathwayService] Refresh already in-progress for ${cacheKey}, skipping.`,
      );
      return null;
    }

    if (!force) {
      const current = await SportPathway.findOne({ cacheKey })
        .select("isVerified")
        .lean();
      if ((current as any)?.isVerified) {
        log.info(
          `[PathwayService] ${cacheKey} is expert-verified — skipping auto-refresh (pass force=true to override).`,
        );
        return null;
      }
    }

    this.refreshInProgressSet.add(cacheKey);
    log.info(`[PathwayService] 🔄 Refreshing pathway: ${cacheKey}`);

    try {
      // Mark in DB for multi-instance safety
      await SportPathway.updateOne(
        { cacheKey },
        {
          $set: {
            contentRefreshInProgress: true,
            financialRefreshInProgress: true,
          },
        },
      );

      // Parse slug / state from cacheKey e.g. "cricket_punjab"
      const parts = cacheKey.split("_");
      const sportSlug: string = parts[0] ?? cacheKey;
      const parsedState = parts.slice(1).join("-");
      const state =
        parsedState && parsedState !== "any" ? parsedState : undefined;

      // Prefer sportName from existing doc
      const existingDoc = await SportPathway.findOne({ cacheKey })
        .select("sportName")
        .lean();
      const sportName: string = String(
        (existingDoc as any)?.sportName || sportSlug,
      );

      const generated = await this.generatePathway(sportName, state);

      if (!generated) {
        log.warn(
          `[PathwayService] Refresh generation returned null for ${cacheKey}`,
        );
        await SportPathway.updateOne(
          { cacheKey },
          {
            $set: {
              contentRefreshInProgress: false,
              financialRefreshInProgress: false,
            },
          },
        );
        return null;
      }

      const refreshed = await SportPathway.findOneAndUpdate(
        { cacheKey },
        {
          $set: {
            ...generated,
            // Ensure canonical fields are never overwritten by Gemini output
            tournaments: [],
            scholarships: [],
            universities: [],
            sportSlug,
            cacheKey,
            contentRefreshedAt: new Date(),
            financialDataRefreshedAt: new Date(),
            contentRefreshInProgress: false,
            financialRefreshInProgress: false,
          },
        },
        { upsert: true, new: true },
      );

      log.info(`[PathwayService] ✅ Pathway refreshed: ${cacheKey}`);

      // Also trigger a scraper refresh for the canonical data
      try {
        await realDataScraperService.scrapeSport({
          sportSlug,
          sportName: String(sportName),
        });
      } catch (scraperErr) {
        log.warn(
          `[PathwayService] Scraper refresh after pathway refresh failed for ${sportSlug}:`,
          scraperErr,
        );
      }

      return refreshed as SportPathwayDocument;
    } catch (err) {
      log.error(`[PathwayService] ❌ Refresh error for ${cacheKey}:`, err);
      await SportPathway.updateOne(
        { cacheKey },
        {
          $set: {
            contentRefreshInProgress: false,
            financialRefreshInProgress: false,
          },
        },
      ).catch(() => {});
      return null;
    } finally {
      this.refreshInProgressSet.delete(cacheKey);
    }
  }

  /**
   * Returns cacheKeys of pathways that haven't been refreshed within thresholdDays.
   * Capped at 50 results per call to avoid hammering Gemini in a single run.
   */
  async getStalePathways(
    thresholdDays: number = DEFAULT_STALE_DAYS,
  ): Promise<string[]> {
    const financialCutoff = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000);
    const contentCutoff = new Date(Date.now() - 180 * 24 * 60 * 60 * 1000);

    const staleDocs = await SportPathway.find({
      $or: [
        { financialDataRefreshedAt: { $exists: false } },
        { financialDataRefreshedAt: null },
        { financialDataRefreshedAt: { $lt: financialCutoff } },
        { contentRefreshedAt: { $exists: false } },
        { contentRefreshedAt: null },
        { contentRefreshedAt: { $lt: contentCutoff } },
      ],
      contentRefreshInProgress: { $ne: true },
      financialRefreshInProgress: { $ne: true },
      // Expert-verified pathways are excluded from automatic regeneration —
      // an AI refresh would silently overwrite reviewed content.
      isVerified: { $ne: true },
    })
      .select("cacheKey")
      .sort({ lastRefreshedAt: 1 }) // oldest first
      .limit(50)
      .lean();

    return staleDocs.map((doc: any) => doc.cacheKey as string).filter(Boolean);
  }

  /**
   * Pre-warm pathways for the top popular Indian sports.
   * Only generates if a generic (age=any, city=any) pathway doesn't already exist.
   * Called once at server startup with a delay.
   */
  async preWarmPopularSports(): Promise<void> {
    log.info("[PathwayService] 🔥 Pre-warming popular sports...");

    for (const sportName of POPULAR_SPORTS) {
      try {
        const slug = toSlug(sportName);
        const cacheKey = `${slug}_any_`;

        const exists = await SportPathway.findOne({ cacheKey })
          .select("_id")
          .lean();

        if (exists) {
          log.info(`[PathwayService] Pre-warm skipped (cached): ${cacheKey}`);
          continue;
        }

        log.info(`[PathwayService] Pre-warming: ${sportName}`);
        const generated = await this.generatePathway(sportName);
        if (generated) {
          await this.savePathway(slug, cacheKey, generated);
          // Also kick off a canonical data scrape for freshly pre-warmed sports
          realDataScraperService
            .scrapeSport({ sportSlug: slug, sportName })
            .catch((err) =>
              log.warn(
                `[PathwayService] Pre-warm scrape failed for ${sportName}:`,
                err,
              ),
            );
          log.info(`[PathwayService] ✅ Pre-warmed: ${sportName}`);
        }

        // Stagger to respect Gemini rate limits
        await new Promise((resolve) => setTimeout(resolve, 2000));
      } catch (err) {
        log.warn(`[PathwayService] Pre-warm failed for ${sportName}:`, err);
      }
    }

    log.info("[PathwayService] ✅ Pre-warming complete.");
  }

  /**
   * Returns basic stats about the pathway collection for admin dashboards.
   */
  async getStats(): Promise<{
    total: number;
    verified: number;
    stale: number;
    topSports: Array<{ sportName: string; lookupCount: number }>;
  }> {
    const cutoff = new Date(
      Date.now() - DEFAULT_STALE_DAYS * 24 * 60 * 60 * 1000,
    );

    const [total, verified, stale, topSports] = await Promise.all([
      SportPathway.countDocuments(),
      SportPathway.countDocuments({ isVerified: true }),
      SportPathway.countDocuments({
        $or: [
          { lastRefreshedAt: { $exists: false } },
          { lastRefreshedAt: null },
          { lastRefreshedAt: { $lt: cutoff } },
        ],
      }),
      SportPathway.find()
        .sort({ lookupCount: -1 })
        .limit(10)
        .select("sportName lookupCount")
        .lean(),
    ]);

    return {
      total,
      verified,
      stale,
      topSports: (topSports as any[]).map((d) => ({
        sportName: d.sportName,
        lookupCount: d.lookupCount,
      })),
    };
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  /**
   * Fetch entities (tournaments/scholarships/universities) for a sport,
   * waiting for the scraper if they aren't in the DB yet.
   * Used by the dedicated /entities endpoint so the client can fetch this
   * in parallel while the skeleton is already displayed.
   */
  async getEntities(
    sportName: string,
    state?: string,
  ): Promise<{ tournaments: any[]; scholarships: any[]; universities: any[] }> {
    const slug = toSlug(sportName);
    const knownSport = await Sport.findOne({ slug });
    const finalSlug = knownSport ? knownSport.slug : slug;
    const finalName = knownSport ? knownSport.name : sportName;

    const stateQuery = this.buildStateQuery(state);

    const [t, s, u] = await Promise.all([
      Tournament.find({ sportSlug: finalSlug, ...stateQuery })
        .sort({ updatedAt: -1 })
        .limit(6)
        .lean(),
      Scholarship.find({ sportSlug: finalSlug, ...stateQuery })
        .sort({ updatedAt: -1 })
        .limit(6)
        .lean(),
      University.find({ sportSlug: finalSlug, ...stateQuery })
        .sort({ updatedAt: -1 })
        .limit(6)
        .lean(),
    ]);

    const missingEntities = t.length === 0 || s.length === 0 || u.length === 0;
    const missingDates =
      t.length > 0 &&
      (t as any[]).some(
        (doc) => !doc.typicalDates && !doc.registrationDeadline,
      );
    const needsRefresh = missingEntities || missingDates;
    if (needsRefresh) {
      log.info(
        `[PathwayService] getEntities: scraping ${finalSlug} (missingEntities=${missingEntities}, missingDates=${missingDates})...`,
      );
      try {
        await realDataScraperService.scrapeSport({
          sportSlug: finalSlug,
          sportName: finalName,
          ...(state ? { state } : {}),
        });
      } catch (err) {
        log.error(
          `[PathwayService] getEntities scraper failed for ${finalSlug}:`,
          err,
        );
      }

      const [t2, s2, u2] = await Promise.all([
        Tournament.find({ sportSlug: finalSlug, ...stateQuery })
          .sort({ updatedAt: -1 })
          .limit(6)
          .lean(),
        Scholarship.find({ sportSlug: finalSlug, ...stateQuery })
          .sort({ updatedAt: -1 })
          .limit(6)
          .lean(),
        University.find({ sportSlug: finalSlug, ...stateQuery })
          .sort({ updatedAt: -1 })
          .limit(6)
          .lean(),
      ]);
      return { tournaments: t2, scholarships: s2, universities: u2 };
    }

    return { tournaments: t, scholarships: s, universities: u };
  }

  /**
   * Overlays live data from the canonical Tournament/Scholarship/University
   * collections onto a pathway response. Non-blocking: if entities are missing,
   * the scraper is fired in the background and empty arrays are returned
   * immediately so the skeleton can be served to the client right away.
   */
  private async attachCanonicalEntities(
    pathway: SportPathwayDocument,
    sportSlug: string,
    sportName?: string,
    state?: string,
  ): Promise<CanonicalAttachResult> {
    const stateQuery = this.buildStateQuery(state);

    const [tournaments, scholarships, universities] = await Promise.all([
      Tournament.find({ sportSlug, ...stateQuery })
        .sort({ updatedAt: -1 })
        .limit(6)
        .lean(),
      Scholarship.find({ sportSlug, ...stateQuery })
        .sort({ updatedAt: -1 })
        .limit(6)
        .lean(),
      University.find({ sportSlug, ...stateQuery })
        .sort({ updatedAt: -1 })
        .limit(6)
        .lean(),
    ]);

    const plain =
      typeof (pathway as any).toObject === "function"
        ? (pathway as any).toObject()
        : pathway;

    const missingEntities =
      tournaments.length === 0 ||
      scholarships.length === 0 ||
      universities.length === 0;
    const missingDates =
      tournaments.length > 0 &&
      (tournaments as any[]).some(
        (t) => !t.typicalDates && !t.registrationDeadline,
      );
    const needsRefresh = missingEntities || missingDates;

    if (needsRefresh && sportName) {
      // Fire scraper in the background — don't block the response.
      log.info(
        `[PathwayService] Stale canonical data for ${sportSlug} (missingEntities=${missingEntities}, missingDates=${missingDates}) — scraper started in background.`,
      );
      realDataScraperService
        .scrapeSport({
          sportSlug,
          sportName,
          ...(state ? { state } : {}),
        })
        .catch((err) =>
          log.error(
            `[PathwayService] Background scraper failed for ${sportSlug}:`,
            err,
          ),
        );
    }

    const plainResponse = {
      ...plain,
      tournaments,
      tournamentsStatus: (plain as any).tournamentsVerifiedEmpty
        ? "verified_empty"
        : tournaments.length === 0
          ? "not_yet_researched"
          : undefined,
      scholarships,
      scholarshipsStatus: (plain as any).scholarshipsVerifiedEmpty
        ? "verified_empty"
        : scholarships.length === 0
          ? "not_yet_researched"
          : undefined,
      universities,
      universitiesStatus: (plain as any).universitiesVerifiedEmpty
        ? "verified_empty"
        : universities.length === 0
          ? "not_yet_researched"
          : undefined,
    } as SportPathwayDocument;

    if (needsRefresh && sportName) {
      return {
        pathway: plainResponse,
        warnings: [],
        entitiesReady: !missingEntities && !missingDates,
      };
    }

    return {
      pathway: plainResponse,
      warnings: [],
      entitiesReady: true,
    };
  }

  private buildStateQuery(state?: string) {
    if (!state) return {};
    const stateRegex = new RegExp(`^${state}$`, "i");
    return {
      $or: [
        { state: stateRegex },
        { state: { $exists: false } },
        { state: null },
        { state: /national/i },
      ],
    };
  }

  private isPathwayStale(doc: SportPathwayDocument): boolean {
    const staleCutoff = new Date(
      Date.now() - 180 * 24 * 60 * 60 * 1000,
    );
    const referenceDate = (doc as any).contentRefreshedAt ?? (doc as any).lastRefreshedAt ?? doc.createdAt;
    return referenceDate < staleCutoff;
  }

  private async validateSport(sportName: string): Promise<boolean> {
    const cacheKey = sportName.trim().toLowerCase();
    if (this.sportValidationCache.has(cacheKey)) {
      return this.sportValidationCache.get(cacheKey)!;
    }

    const prompt = `Is "${sportName}" a real sport or athletic activity? Reply with only "yes" or "no".`;

    if (this.genAI) {
      try {
        const result = await this.genAI.models.generateContent({
          model: "gemini-2.5-flash-lite",
          contents: prompt,
          config: {
            maxOutputTokens: 5,
          },
        });
        
        if (result.usageMetadata) {
          log.info(
            `[PathwayService] Validation usage. Model: gemini-2.5-flash-lite, Prompt: ${result.usageMetadata.promptTokenCount}, Candidates: ${result.usageMetadata.candidatesTokenCount}, Total: ${result.usageMetadata.totalTokenCount}`,
          );
        }

        const answer = (result.text ?? "").trim().toLowerCase();
        const isValid = answer.startsWith("yes");
        
        if (this.sportValidationCache.size >= 500) {
          const firstKey = this.sportValidationCache.keys().next().value;
          this.sportValidationCache.delete(firstKey!);
        }
        this.sportValidationCache.set(cacheKey, isValid);
        return isValid;
      } catch (err) {
        log.warn(
          "[PathwayService] Gemini validation failed, falling back.",
          err,
        );
      }
    }

    return true; // Fail open — generate anyway if API unavailable
  }

  private async generatePathway(
    sportName: string,
    state?: string,
  ): Promise<{
    sportName: string;
    category: string;
    overview: string;
    governingBodyNational: string;
    levels: Array<{
      level: number;
      label: string;
      title: string;
      description: string;
      keyFocus: string;
      ageRange: string;
      competitions: string;
      steps: string[];
      governingBody: string;
    }>;
    equipment: Array<{
      level: string;
      items: string[];
      estimatedCost: string;
    }>;
    careers: Array<{
      role: string;
      description: string;
      demand: string;
    }>;
  } | null> {
    if (!this.genAI) return null;

    const modelCandidates = [
      "gemini-2.5-flash",
      "gemini-3.5-flash",
      "gemini-2.5-flash-lite",
    ].filter(Boolean) as string[];

    const callModelWithFallback = async (
      prompt: string,
      isMeta: boolean,
      levelNums?: number[],
    ) => {
      let attempts = 0;
      for (const modelName of modelCandidates) {
        if (attempts >= modelCandidates.length) break;
        attempts++;
        const startTime = Date.now();
        const controller = new AbortController();
        const timeoutMs = isMeta ? 8000 : 12000;
        const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

        try {
          const withTimeout = <T>(p: Promise<T>, ms: number) =>
            Promise.race([
              p,
              new Promise<never>((_, reject) =>
                setTimeout(() => reject(new Error("client_timeout")), ms),
              ),
            ]);

          const result = await withTimeout(
            this.genAI!.models.generateContent({
              model: modelName,
              contents: prompt,
              config: {
                responseMimeType: "application/json",
                temperature: 0.4,
                abortSignal: controller.signal,
                maxOutputTokens: isMeta ? 1024 : 3072,
              },
            }),
            timeoutMs,
          );
          clearTimeout(timeoutId);

          const latencyMs = Date.now() - startTime;
          const text = (result.text ?? "").trim();
          const jsonText = text
            .replace(/^```[a-z]*\n?/i, "")
            .replace(/```$/i, "")
            .trim();
          const parsed = JSON.parse(jsonText);

          log.info(
            `[PathwayService] ${isMeta ? "Meta" : `Levels ${levelNums?.join(",")}`} generation success. Model: ${modelName}, Attempt: ${attempts}, Latency: ${latencyMs}ms`,
          );
          
          if (result.usageMetadata) {
            log.info(
              `[PathwayService] Usage [${isMeta ? "Meta" : `Levels ${levelNums?.join(",")}`}]. Model: ${modelName}, Prompt: ${result.usageMetadata.promptTokenCount}, Candidates: ${result.usageMetadata.candidatesTokenCount}, Total: ${result.usageMetadata.totalTokenCount}`,
            );
          }

          if (!isMeta) {
            // Level validation (benchmarks length check)
            const parsedArray = Array.isArray(parsed) ? parsed : [parsed];
            for (const lvl of parsedArray) {
              const ageRangeStr = lvl.ageRange || "";
              const matches = ageRangeStr.match(/(\d+)\s*[-–]\s*(\d+)/);
              if (matches) {
                const lower = parseInt(matches[1], 10);
                const upper = parseInt(matches[2], 10);
                if (upper - lower > 1) {
                  const metrics = lvl.benchmarks?.metrics || [];
                  if (metrics.length < 3) {
                    throw new Error(
                      `Level ${lvl.level} spans > 1 year but has < 3 benchmark metrics`,
                    );
                  }
                }
              }
            }
          }

          return parsed;
        } catch (error: any) {
          clearTimeout(timeoutId);
          const latencyMs = Date.now() - startTime;
          const reason =
            error.name === "AbortError" ? "Timeout" : error.message;
          log.warn(
            `[PathwayService] ${isMeta ? "Meta" : `Levels ${levelNums?.join(",")}`} generation failed. Model: ${modelName}, Attempt: ${attempts}, Latency: ${latencyMs}ms, Reason: ${reason}`,
          );
        }
      }

      // Fallback if all attempts fail
      if (isMeta) {
        return null;
      } else {
        return levelNums!.map((levelNum) => ({
          level: levelNum,
          label:
            levelNum === 1 ? "Beginner" : LEVEL_LABEL_FALLBACKS[levelNum - 1],
          title: "Pathway Level",
          description: "Information currently unavailable.",
          keyFocus: "General",
          ageRange: "Varies",
          competitions: "Varies",
          steps: [],
          governingBody: "",
          localResources: {
            academies: [],
            facilities: [],
            governingBodies: [],
          },
          benchmarks: { description: "", metrics: [] },
          trialInfo: {
            typicalMonths: "",
            precisionLevel: "",
            registrationProcess: "",
            eligibilityAge: "",
            selectionCriteria: [],
            tips: [],
          },
          injuryRisks: {
            commonInjuries: [],
            preventionTips: [],
            warningSignsToWatch: [],
          },
          talentSignals: {
            physicalMarkers: [],
            cognitiveMarkers: [],
            behavioralMarkers: [],
          },
          mentalSkillsFocus: [],
          coachSelectionGuide: {
            mustHave: [],
            niceToHave: [],
            redFlags: [],
            questionsToAsk: [],
          },
          governmentSchemes: [],
          academicIntegration: "",
          proactiveDocuments: [],
        }));
      }
    };

    const [metaResult, levelsAResult, levelsBResult] = await Promise.all([
      callModelWithFallback(buildPathwayMetaPrompt(sportName, state), true),
      callModelWithFallback(buildLevelRangePrompt(sportName, state, [1, 2, 3]), false, [1, 2, 3]),
      callModelWithFallback(buildLevelRangePrompt(sportName, state, [4, 5]), false, [4, 5]),
    ]);

    if (!metaResult) {
      log.error(
        "[PathwayService] Meta pathway generation failed all attempts.",
      );
      return null;
    }

    let flatLevels: any[] = [];
    if (levelsAResult) {
      flatLevels = flatLevels.concat(Array.isArray(levelsAResult) ? levelsAResult : [levelsAResult]);
    }
    if (levelsBResult) {
      flatLevels = flatLevels.concat(Array.isArray(levelsBResult) ? levelsBResult : [levelsBResult]);
    }
    // ensure order by level
    flatLevels.sort((a, b) => a.level - b.level);

    const levels = flatLevels.map((lvl: any, index: number) => {
      return {
        ...lvl,
        label:
          index === 0
            ? "Beginner"
            : lvl.label?.trim() || LEVEL_LABEL_FALLBACKS[index],
      };
    });

    return {
      sportName: metaResult.sportName,
      category: metaResult.category,
      overview: metaResult.overview,
      governingBodyNational: metaResult.governingBodyNational,
      levels,
      equipment: metaResult.equipment,
      careers: metaResult.careers,
    } as any;
  }

  private async savePathway(
    slug: string,
    cacheKey: string,
    data: {
      sportName: string;
      category: string;
      overview: string;
      levels: Array<{
        level: number;
        label: string;
        title: string;
        description: string;
        keyFocus: string;
        ageRange: string;
        competitions: string;
        steps: string[];
        governingBody: string;
      }>;
      equipment: Array<any>;
      careers: Array<any>;
    },
  ): Promise<SportPathwayDocument> {
    const docData = {
      sportSlug: slug,
      cacheKey,
      sportName: data.sportName || slug,
      category: data.category || "Other",
      overview: data.overview || "",
      levels: data.levels,
      // Tournaments/scholarships/universities are NEVER written here — they
      // live exclusively in the canonical collections and get attached at
      // read time via attachCanonicalEntities().
      tournaments: [],
      scholarships: [],
      universities: [],
      equipment: data.equipment || [],
      careers: data.careers || [],
      isVerified: false,
      lastRefreshedAt: new Date(),
      refreshInProgress: false,
    };

    const saved = await SportPathway.findOneAndUpdate(
      { cacheKey },
      {
        $setOnInsert: docData,
        $inc: { lookupCount: 1 },
      },
      { upsert: true, new: true },
    );

    return saved as SportPathwayDocument;
  }
}

export const pathwayService = new PathwayService();
