// ─── Find-Sport Scoring — Testing Only ─────────────────────────────────────
// Server-side twin of client/src/modules/find-sport/data/sportProfiles.ts's
// SPORT_PROFILES + PRIOR_SPORTS_OPTIONS (the CITIES export isn't needed for
// scoring, so it's skipped). See findSportTestScorer.ts for context.

import type { SportProfile } from "./findSportTestTypes";

export const SPORT_PROFILES: SportProfile[] = [
  {
    id: "badminton",
    name: "Badminton",
    category: "racket",
    individual: 4,
    explosive: 5,
    endurance: 3,
    visualTracking: 5,
    reactFast: 5,
    sustainedFocus: 3,
    pressureTolerance: 5,
    repetitionNeed: 4,
    contactRequired: 1,
    visionDemand: 4,
    agilityNeed: 5,
    minWeeklyHours: 6,
    buildPreference: "lean",
    heightAdvantage: "any",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "3k-7k",
    minCityTier: 2,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [5, 10],
    ageWindowCutoff: 14,
    specializationIntensity: "high",
    costRange: "₹4,000 – 8,000/month",
    tagline: "One of the fastest racket sports in the world",
  },
  {
    id: "tennis",
    name: "Tennis",
    category: "racket",
    individual: 5,
    explosive: 4,
    endurance: 4,
    visualTracking: 5,
    reactFast: 4,
    sustainedFocus: 4,
    pressureTolerance: 5,
    repetitionNeed: 5,
    contactRequired: 1,
    visionDemand: 4,
    agilityNeed: 4,
    minWeeklyHours: 8,
    buildPreference: "lean",
    heightAdvantage: "tall",
    environmentPreference: "outdoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "7k-15k",
    minCityTier: 2,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [5, 10],
    ageWindowCutoff: 15,
    specializationIntensity: "high",
    costRange: "₹8,000 – 18,000/month",
    tagline: "Individual excellence, global pathway",
  },
  {
    id: "cricket",
    name: "Cricket",
    category: "field",
    individual: 3,
    explosive: 3,
    endurance: 4,
    visualTracking: 5,
    reactFast: 3,
    sustainedFocus: 5,
    pressureTolerance: 4,
    repetitionNeed: 5,
    contactRequired: 1,
    visionDemand: 4,
    agilityNeed: 2,
    minWeeklyHours: 6,
    buildPreference: "any",
    heightAdvantage: "any",
    environmentPreference: "outdoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "flexible",
    ageWindowIdeal: [6, 14],
    ageWindowCutoff: 18,
    specializationIntensity: "low",
    costRange: "₹2,000 – 8,000/month",
    tagline: "India's most supported sport pathway",
  },
  {
    id: "football",
    name: "Football",
    category: "field",
    individual: 1,
    explosive: 5,
    endurance: 5,
    visualTracking: 3,
    reactFast: 4,
    sustainedFocus: 2,
    pressureTolerance: 2,
    repetitionNeed: 3,
    contactRequired: 3,
    visionDemand: 3,
    agilityNeed: 4,
    minWeeklyHours: 5,
    buildPreference: "any",
    heightAdvantage: "any",
    environmentPreference: "outdoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [5, 13],
    ageWindowCutoff: 16,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 5,000/month",
    tagline: "Team sport with the lowest entry barrier",
  },
  {
    id: "swimming",
    name: "Swimming",
    category: "water",
    individual: 4,
    explosive: 2,
    endurance: 5,
    visualTracking: 1,
    reactFast: 2,
    sustainedFocus: 5,
    pressureTolerance: 4,
    repetitionNeed: 5,
    contactRequired: 1,
    visionDemand: 1,
    agilityNeed: 2,
    minWeeklyHours: 8,
    buildPreference: "lean",
    heightAdvantage: "tall",
    environmentPreference: "indoor",
    requiresWater: true,
    requiresContact: false,
    minBudgetTier: "3k-7k",
    minCityTier: 2,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [4, 9],
    ageWindowCutoff: 13,
    specializationIntensity: "high",
    costRange: "₹4,000 – 10,000/month",
    tagline: "Builds discipline and full-body fitness",
  },
  {
    id: "gymnastics",
    name: "Gymnastics",
    category: "gymnastics",
    individual: 5,
    explosive: 5,
    endurance: 3,
    visualTracking: 2,
    reactFast: 3,
    sustainedFocus: 5,
    pressureTolerance: 5,
    repetitionNeed: 5,
    contactRequired: 1,
    visionDemand: 2,
    agilityNeed: 5,
    minWeeklyHours: 12,
    buildPreference: "lean",
    heightAdvantage: "short",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "7k-15k",
    minCityTier: 1,
    ageStartSensitivity: "critical",
    ageWindowIdeal: [3, 7],
    ageWindowCutoff: 10,
    specializationIntensity: "high",
    costRange: "₹8,000 – 20,000/month",
    tagline: "Precision, strength, and total body control",
  },
  {
    id: "chess",
    name: "Chess",
    category: "mind",
    individual: 5,
    explosive: 1,
    endurance: 4,
    visualTracking: 1,
    reactFast: 1,
    sustainedFocus: 5,
    pressureTolerance: 5,
    repetitionNeed: 4,
    contactRequired: 1,
    visionDemand: 1,
    agilityNeed: 1,
    minWeeklyHours: 2,
    buildPreference: "any",
    heightAdvantage: "any",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "flexible",
    ageWindowIdeal: [4, 14],
    ageWindowCutoff: 99,
    specializationIntensity: "low",
    costRange: "₹500 – 3,000/month",
    tagline: "India punches above its weight in international chess",
  },
  {
    id: "table-tennis",
    name: "Table Tennis",
    category: "racket",
    individual: 4,
    explosive: 5,
    endurance: 3,
    visualTracking: 5,
    reactFast: 5,
    sustainedFocus: 3,
    pressureTolerance: 4,
    repetitionNeed: 4,
    contactRequired: 1,
    visionDemand: 5,
    agilityNeed: 4,
    minWeeklyHours: 5,
    buildPreference: "lean",
    heightAdvantage: "any",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [5, 11],
    ageWindowCutoff: 15,
    specializationIntensity: "high",
    costRange: "₹1,500 – 5,000/month",
    tagline: "Fast, sharp, affordable — widely available across India",
  },
  {
    id: "basketball",
    name: "Basketball",
    category: "indoor",
    individual: 2,
    explosive: 5,
    endurance: 4,
    visualTracking: 4,
    reactFast: 4,
    sustainedFocus: 3,
    pressureTolerance: 3,
    repetitionNeed: 4,
    contactRequired: 3,
    visionDemand: 3,
    agilityNeed: 4,
    minWeeklyHours: 5,
    buildPreference: "any",
    heightAdvantage: "tall",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 2,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [6, 14],
    ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹2,000 – 7,000/month",
    tagline: "Team sport where height is a genuine advantage",
  },
  {
    id: "kabaddi",
    name: "Kabaddi",
    category: "combat",
    individual: 2,
    explosive: 5,
    endurance: 3,
    visualTracking: 2,
    reactFast: 5,
    sustainedFocus: 2,
    pressureTolerance: 3,
    repetitionNeed: 3,
    contactRequired: 5,
    visionDemand: 2,
    agilityNeed: 5,
    minWeeklyHours: 5,
    buildPreference: "stocky",
    heightAdvantage: "any",
    environmentPreference: "either",
    requiresWater: false,
    requiresContact: true,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "flexible",
    ageWindowIdeal: [7, 14],
    ageWindowCutoff: 17,
    specializationIntensity: "low",
    costRange: "₹500 – 3,000/month",
    tagline: "India's national sport — PKL has opened a serious career path",
  },
  {
    id: "wrestling",
    name: "Wrestling",
    category: "combat",
    individual: 5,
    explosive: 4,
    endurance: 4,
    visualTracking: 2,
    reactFast: 4,
    sustainedFocus: 4,
    pressureTolerance: 5,
    repetitionNeed: 5,
    contactRequired: 5,
    visionDemand: 2,
    agilityNeed: 3,
    minWeeklyHours: 6,
    buildPreference: "stocky",
    heightAdvantage: "short",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: true,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "flexible",
    ageWindowIdeal: [7, 13],
    ageWindowCutoff: 16,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 4,000/month",
    tagline: "India's strongest Olympic medal sport",
  },
  {
    id: "shooting",
    name: "Shooting",
    category: "precision",
    individual: 5,
    explosive: 1,
    endurance: 3,
    visualTracking: 3,
    reactFast: 1,
    sustainedFocus: 5,
    pressureTolerance: 5,
    repetitionNeed: 5,
    contactRequired: 1,
    visionDemand: 5,
    agilityNeed: 1,
    minWeeklyHours: 8,
    buildPreference: "any",
    heightAdvantage: "any",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "7k-15k",
    minCityTier: 1,
    ageStartSensitivity: "flexible",
    ageWindowIdeal: [8, 15],
    ageWindowCutoff: 22,
    specializationIntensity: "moderate",
    costRange: "₹8,000 – 25,000/month",
    tagline: "India's most decorated Olympic discipline",
  },
  {
    id: "athletics",
    name: "Athletics",
    category: "athletics",
    individual: 4,
    explosive: 4,
    endurance: 5,
    visualTracking: 2,
    reactFast: 4,
    sustainedFocus: 4,
    pressureTolerance: 5,
    repetitionNeed: 5,
    contactRequired: 1,
    visionDemand: 2,
    agilityNeed: 3,
    minWeeklyHours: 5,
    buildPreference: "lean",
    heightAdvantage: "any",
    environmentPreference: "outdoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [7, 14],
    ageWindowCutoff: 18,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 5,000/month",
    tagline: "Track and field — Neeraj Chopra opened a new era",
  },
  {
    id: "volleyball",
    name: "Volleyball",
    category: "field",
    individual: 2,
    explosive: 5,
    endurance: 4,
    visualTracking: 4,
    reactFast: 4,
    sustainedFocus: 3,
    pressureTolerance: 3,
    repetitionNeed: 4,
    contactRequired: 1,
    visionDemand: 3,
    agilityNeed: 4,
    minWeeklyHours: 5,
    buildPreference: "lean",
    heightAdvantage: "tall",
    environmentPreference: "either",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [8, 14],
    ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 5,000/month",
    tagline: "Team sport where height unlocks a clear advantage",
  },
  {
    id: "hockey",
    name: "Hockey",
    category: "field",
    individual: 1,
    explosive: 4,
    endurance: 4,
    visualTracking: 4,
    reactFast: 4,
    sustainedFocus: 3,
    pressureTolerance: 3,
    repetitionNeed: 4,
    contactRequired: 3,
    visionDemand: 3,
    agilityNeed: 4,
    minWeeklyHours: 6,
    buildPreference: "any",
    heightAdvantage: "any",
    environmentPreference: "outdoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [6, 13],
    ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 5,000/month",
    tagline: "India's most decorated Olympic team sport, with a growing revival",
  },
  {
    id: "boxing",
    name: "Boxing",
    category: "combat",
    individual: 5,
    explosive: 5,
    endurance: 4,
    visualTracking: 3,
    reactFast: 4,
    sustainedFocus: 4,
    pressureTolerance: 5,
    repetitionNeed: 5,
    contactRequired: 5,
    visionDemand: 3,
    agilityNeed: 4,
    minWeeklyHours: 6,
    buildPreference: "any",
    heightAdvantage: "any",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: true,
    minBudgetTier: "under-3k",
    minCityTier: 3,
    ageStartSensitivity: "flexible",
    ageWindowIdeal: [8, 14],
    ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 4,000/month",
    tagline: "India's fastest-growing Olympic combat sport",
  },
  {
    id: "cycling",
    name: "Cycling",
    category: "athletics",
    individual: 4,
    explosive: 3,
    endurance: 5,
    visualTracking: 2,
    reactFast: 2,
    sustainedFocus: 4,
    pressureTolerance: 4,
    repetitionNeed: 5,
    contactRequired: 1,
    visionDemand: 2,
    agilityNeed: 2,
    minWeeklyHours: 6,
    buildPreference: "lean",
    heightAdvantage: "any",
    environmentPreference: "outdoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "7k-15k",
    minCityTier: 2,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [8, 14],
    ageWindowCutoff: 18,
    specializationIntensity: "moderate",
    costRange: "₹6,000 – 15,000/month",
    tagline: "A growing endurance sport with Olympic track & road pathways",
  },
  {
    id: "skating",
    name: "Skating",
    category: "indoor",
    individual: 5,
    explosive: 4,
    endurance: 4,
    visualTracking: 2,
    reactFast: 3,
    sustainedFocus: 4,
    pressureTolerance: 4,
    repetitionNeed: 5,
    contactRequired: 2,
    visionDemand: 2,
    agilityNeed: 4,
    minWeeklyHours: 6,
    buildPreference: "lean",
    heightAdvantage: "any",
    environmentPreference: "indoor",
    requiresWater: false,
    requiresContact: false,
    minBudgetTier: "3k-7k",
    minCityTier: 2,
    ageStartSensitivity: "moderate",
    ageWindowIdeal: [5, 12],
    ageWindowCutoff: 16,
    specializationIntensity: "moderate",
    costRange: "₹3,000 – 8,000/month",
    tagline: "A fast-growing individual speed sport with strong junior participation",
  },
  {
    id: "kho-kho",
    name: "Kho-Kho",
    category: "field",
    individual: 2, explosive: 5, endurance: 3, visualTracking: 3, reactFast: 5,
    sustainedFocus: 2, pressureTolerance: 3, repetitionNeed: 3, contactRequired: 2,
    visionDemand: 3, agilityNeed: 5, minWeeklyHours: 5,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "either",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 3,
    ageStartSensitivity: "flexible", ageWindowIdeal: [7, 14], ageWindowCutoff: 17,
    specializationIntensity: "low",
    costRange: "₹500 – 2,000/month",
    tagline: "A traditional Indian sport with explosive speed and a new professional league",
  },
  {
    id: "mallakhamb",
    name: "Mallakhamb",
    category: "gymnastics",
    individual: 5, explosive: 4, endurance: 3, visualTracking: 1, reactFast: 2,
    sustainedFocus: 5, pressureTolerance: 5, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 1, agilityNeed: 5, minWeeklyHours: 8,
    buildPreference: "lean", heightAdvantage: "short", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "critical", ageWindowIdeal: [5, 10], ageWindowCutoff: 13,
    specializationIntensity: "moderate",
    costRange: "₹1,500 – 4,000/month",
    tagline: "India's own gymnastic art form, built on strength and balance",
  },
  {
    id: "judo",
    name: "Judo",
    category: "combat",
    individual: 4, explosive: 4, endurance: 3, visualTracking: 2, reactFast: 3,
    sustainedFocus: 4, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 5,
    visionDemand: 2, agilityNeed: 3, minWeeklyHours: 6,
    buildPreference: "stocky", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: true,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "flexible", ageWindowIdeal: [7, 13], ageWindowCutoff: 16,
    specializationIntensity: "moderate",
    costRange: "₹1,500 – 4,500/month",
    tagline: "Olympic throwing and grappling art growing fast in Indian SAI centres",
  },
  {
    id: "taekwondo",
    name: "Taekwondo",
    category: "combat",
    individual: 4, explosive: 5, endurance: 3, visualTracking: 3, reactFast: 5,
    sustainedFocus: 3, pressureTolerance: 4, repetitionNeed: 4, contactRequired: 3,
    visionDemand: 3, agilityNeed: 5, minWeeklyHours: 5,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: true,
    minBudgetTier: "under-3k", minCityTier: 3,
    ageStartSensitivity: "moderate", ageWindowIdeal: [6, 12], ageWindowCutoff: 16,
    specializationIntensity: "low",
    costRange: "₹1,000 – 3,000/month",
    tagline: "One of the most widely available martial arts for kids in India",
  },
  {
    id: "karate",
    name: "Karate",
    category: "combat",
    individual: 4, explosive: 4, endurance: 3, visualTracking: 3, reactFast: 4,
    sustainedFocus: 4, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 3,
    visionDemand: 3, agilityNeed: 4, minWeeklyHours: 5,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: true,
    minBudgetTier: "under-3k", minCityTier: 3,
    ageStartSensitivity: "moderate", ageWindowIdeal: [6, 12], ageWindowCutoff: 16,
    specializationIntensity: "low",
    costRange: "₹800 – 2,500/month",
    tagline: "The most common martial art academy in Indian neighbourhoods",
  },
  {
    id: "fencing",
    name: "Fencing",
    category: "combat",
    individual: 5, explosive: 4, endurance: 3, visualTracking: 5, reactFast: 5,
    sustainedFocus: 4, pressureTolerance: 4, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 5, agilityNeed: 3, minWeeklyHours: 6,
    buildPreference: "lean", heightAdvantage: "tall", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 1,
    ageStartSensitivity: "moderate", ageWindowIdeal: [8, 14], ageWindowCutoff: 18,
    specializationIntensity: "high",
    costRange: "₹8,000 – 18,000/month",
    tagline: "A precision duelling sport with growing SAI investment in India",
  },
  {
    id: "archery",
    name: "Archery",
    category: "precision",
    individual: 5, explosive: 1, endurance: 3, visualTracking: 3, reactFast: 1,
    sustainedFocus: 5, pressureTolerance: 5, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 5, agilityNeed: 1, minWeeklyHours: 6,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "either",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 2,
    ageStartSensitivity: "flexible", ageWindowIdeal: [8, 15], ageWindowCutoff: 20,
    specializationIntensity: "moderate",
    costRange: "₹6,000 – 15,000/month",
    tagline: "India's strong tribal-belt tradition meets an Olympic pathway",
  },
  {
    id: "weightlifting",
    name: "Weightlifting",
    category: "athletics",
    individual: 5, explosive: 5, endurance: 2, visualTracking: 1, reactFast: 2,
    sustainedFocus: 4, pressureTolerance: 5, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 1, agilityNeed: 2, minWeeklyHours: 6,
    buildPreference: "stocky", heightAdvantage: "short", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "moderate", ageWindowIdeal: [10, 15], ageWindowCutoff: 18,
    specializationIntensity: "moderate",
    costRange: "₹1,500 – 4,000/month",
    tagline: "India's growing Olympic strength discipline, led by Mirabai Chanu's rise",
  },
  {
    id: "powerlifting",
    name: "Powerlifting",
    category: "athletics",
    individual: 5, explosive: 4, endurance: 2, visualTracking: 1, reactFast: 1,
    sustainedFocus: 4, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 1, agilityNeed: 1, minWeeklyHours: 6,
    buildPreference: "stocky", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "flexible", ageWindowIdeal: [12, 16], ageWindowCutoff: 20,
    specializationIntensity: "low",
    costRange: "₹1,000 – 3,000/month",
    tagline: "A growing raw-strength sport with an accessible gym-based pathway",
  },
  {
    id: "squash",
    name: "Squash",
    category: "racket",
    individual: 5, explosive: 4, endurance: 5, visualTracking: 5, reactFast: 5,
    sustainedFocus: 4, pressureTolerance: 5, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 4, agilityNeed: 5, minWeeklyHours: 7,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 1,
    ageStartSensitivity: "moderate", ageWindowIdeal: [6, 11], ageWindowCutoff: 15,
    specializationIntensity: "high",
    costRange: "₹7,000 – 15,000/month",
    tagline: "India punches well above its weight globally in squash",
  },
  {
    id: "handball",
    name: "Handball",
    category: "indoor",
    individual: 1, explosive: 5, endurance: 4, visualTracking: 4, reactFast: 4,
    sustainedFocus: 2, pressureTolerance: 3, repetitionNeed: 3, contactRequired: 3,
    visionDemand: 3, agilityNeed: 4, minWeeklyHours: 5,
    buildPreference: "any", heightAdvantage: "tall", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "moderate", ageWindowIdeal: [7, 14], ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 4,000/month",
    tagline: "A fast, growing Olympic team sport with low equipment cost",
  },
  {
    id: "netball",
    name: "Netball",
    category: "indoor",
    individual: 1, explosive: 4, endurance: 4, visualTracking: 4, reactFast: 4,
    sustainedFocus: 3, pressureTolerance: 3, repetitionNeed: 3, contactRequired: 2,
    visionDemand: 3, agilityNeed: 4, minWeeklyHours: 5,
    buildPreference: "any", heightAdvantage: "tall", environmentPreference: "either",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "moderate", ageWindowIdeal: [8, 14], ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹1,000 – 3,000/month",
    tagline: "A popular girls' team sport with a clean, non-contact rule set",
  },
  {
    id: "rugby",
    name: "Rugby",
    category: "field",
    individual: 1, explosive: 5, endurance: 5, visualTracking: 3, reactFast: 4,
    sustainedFocus: 2, pressureTolerance: 3, repetitionNeed: 3, contactRequired: 5,
    visionDemand: 3, agilityNeed: 4, minWeeklyHours: 6,
    buildPreference: "stocky", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: true,
    minBudgetTier: "under-3k", minCityTier: 3,
    ageStartSensitivity: "moderate", ageWindowIdeal: [8, 14], ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹500 – 3,000/month",
    tagline: "A fast-growing contact team sport with strong grassroots programs",
  },
  {
    id: "water-polo",
    name: "Water Polo",
    category: "water",
    individual: 1, explosive: 4, endurance: 5, visualTracking: 4, reactFast: 4,
    sustainedFocus: 3, pressureTolerance: 3, repetitionNeed: 4, contactRequired: 4,
    visionDemand: 3, agilityNeed: 3, minWeeklyHours: 8,
    buildPreference: "any", heightAdvantage: "tall", environmentPreference: "indoor",
    requiresWater: true, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 1,
    ageStartSensitivity: "moderate", ageWindowIdeal: [9, 14], ageWindowCutoff: 17,
    specializationIntensity: "high",
    costRange: "₹6,000 – 14,000/month",
    tagline: "A demanding aquatic team sport for strong swimmers who love contact",
  },
  {
    id: "diving",
    name: "Diving",
    category: "water",
    individual: 5, explosive: 5, endurance: 2, visualTracking: 2, reactFast: 3,
    sustainedFocus: 4, pressureTolerance: 5, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 2, agilityNeed: 5, minWeeklyHours: 8,
    buildPreference: "lean", heightAdvantage: "short", environmentPreference: "indoor",
    requiresWater: true, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 1,
    ageStartSensitivity: "critical", ageWindowIdeal: [5, 9], ageWindowCutoff: 12,
    specializationIntensity: "high",
    costRange: "₹6,000 – 15,000/month",
    tagline: "A small but real Olympic pathway, needs an early start and rare facilities",
  },
  {
    id: "rowing",
    name: "Rowing",
    category: "water",
    individual: 3, explosive: 3, endurance: 5, visualTracking: 1, reactFast: 2,
    sustainedFocus: 5, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 1, agilityNeed: 2, minWeeklyHours: 8,
    buildPreference: "any", heightAdvantage: "tall", environmentPreference: "outdoor",
    requiresWater: true, requiresContact: false,
    minBudgetTier: "3k-7k", minCityTier: 2,
    ageStartSensitivity: "moderate", ageWindowIdeal: [10, 15], ageWindowCutoff: 18,
    specializationIntensity: "moderate",
    costRange: "₹3,000 – 8,000/month",
    tagline: "An endurance water sport backed by dedicated SAI training centres",
  },
  {
    id: "sailing",
    name: "Sailing",
    category: "water",
    individual: 4, explosive: 2, endurance: 3, visualTracking: 3, reactFast: 3,
    sustainedFocus: 4, pressureTolerance: 4, repetitionNeed: 3, contactRequired: 1,
    visionDemand: 3, agilityNeed: 3, minWeeklyHours: 6,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: true, requiresContact: false,
    minBudgetTier: "15k-plus", minCityTier: 1,
    ageStartSensitivity: "flexible", ageWindowIdeal: [10, 16], ageWindowCutoff: 20,
    specializationIntensity: "high",
    costRange: "₹15,000 – 35,000/month",
    tagline: "A coastal-city sport with real Asian Games medal pedigree",
  },
  {
    id: "golf",
    name: "Golf",
    category: "precision",
    individual: 5, explosive: 2, endurance: 3, visualTracking: 3, reactFast: 1,
    sustainedFocus: 5, pressureTolerance: 5, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 4, agilityNeed: 2, minWeeklyHours: 6,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "15k-plus", minCityTier: 1,
    ageStartSensitivity: "flexible", ageWindowIdeal: [6, 14], ageWindowCutoff: 20,
    specializationIntensity: "high",
    costRange: "₹15,000 – 40,000/month",
    tagline: "A high-cost but high-ceiling individual sport with a real Indian pro tour",
  },
  {
    id: "equestrian",
    name: "Equestrian",
    category: "precision",
    individual: 5, explosive: 2, endurance: 3, visualTracking: 2, reactFast: 3,
    sustainedFocus: 4, pressureTolerance: 5, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 2, agilityNeed: 3, minWeeklyHours: 6,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "15k-plus", minCityTier: 1,
    ageStartSensitivity: "moderate", ageWindowIdeal: [8, 14], ageWindowCutoff: 18,
    specializationIntensity: "high",
    costRange: "₹20,000 – 50,000/month",
    tagline: "India's most exclusive Olympic discipline, with real Asian Games success",
  },
  {
    id: "skateboarding",
    name: "Skateboarding",
    category: "indoor",
    individual: 5, explosive: 4, endurance: 2, visualTracking: 2, reactFast: 4,
    sustainedFocus: 3, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 2, agilityNeed: 5, minWeeklyHours: 5,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "3k-7k", minCityTier: 2,
    ageStartSensitivity: "moderate", ageWindowIdeal: [6, 13], ageWindowCutoff: 17,
    specializationIntensity: "moderate",
    costRange: "₹2,000 – 6,000/month",
    tagline: "A newly-Olympic sport riding a wave of Indian skate-park culture",
  },
  {
    id: "sport-climbing",
    name: "Sport Climbing",
    category: "gymnastics",
    individual: 5, explosive: 4, endurance: 4, visualTracking: 2, reactFast: 3,
    sustainedFocus: 5, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 2, agilityNeed: 5, minWeeklyHours: 6,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "3k-7k", minCityTier: 1,
    ageStartSensitivity: "moderate", ageWindowIdeal: [7, 14], ageWindowCutoff: 18,
    specializationIntensity: "high",
    costRange: "₹3,000 – 8,000/month",
    tagline: "A newly-Olympic sport with a fast-growing Indian climbing-gym scene",
  },
  {
    id: "triathlon",
    name: "Triathlon",
    category: "athletics",
    individual: 5, explosive: 2, endurance: 5, visualTracking: 1, reactFast: 1,
    sustainedFocus: 5, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 1, agilityNeed: 2, minWeeklyHours: 10,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: true, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 2,
    ageStartSensitivity: "flexible", ageWindowIdeal: [10, 16], ageWindowCutoff: 20,
    specializationIntensity: "moderate",
    costRange: "₹7,000 – 16,000/month",
    tagline: "A demanding endurance combination sport with a growing Indian race circuit",
  },
  {
    id: "snooker-billiards",
    name: "Snooker/Billiards",
    category: "mind",
    individual: 5, explosive: 1, endurance: 2, visualTracking: 3, reactFast: 1,
    sustainedFocus: 5, pressureTolerance: 5, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 4, agilityNeed: 1, minWeeklyHours: 4,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "3k-7k", minCityTier: 2,
    ageStartSensitivity: "flexible", ageWindowIdeal: [8, 16], ageWindowCutoff: 99,
    specializationIntensity: "moderate",
    costRange: "₹2,500 – 6,000/month",
    tagline: "India has produced multiple world champions in this precision cue sport",
  },
  {
    id: "carrom",
    name: "Carrom",
    category: "mind",
    individual: 4, explosive: 2, endurance: 2, visualTracking: 3, reactFast: 3,
    sustainedFocus: 4, pressureTolerance: 4, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 3, agilityNeed: 1, minWeeklyHours: 3,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 3,
    ageStartSensitivity: "flexible", ageWindowIdeal: [6, 14], ageWindowCutoff: 99,
    specializationIntensity: "low",
    costRange: "₹500 – 1,500/month",
    tagline: "A beloved Indian tabletop game with its own national federation",
  },
  {
    id: "baseball",
    name: "Baseball",
    category: "field",
    individual: 2, explosive: 4, endurance: 3, visualTracking: 5, reactFast: 5,
    sustainedFocus: 3, pressureTolerance: 3, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 5, agilityNeed: 3, minWeeklyHours: 5,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "moderate", ageWindowIdeal: [7, 14], ageWindowCutoff: 17,
    specializationIntensity: "high",
    costRange: "₹1,500 – 4,000/month",
    tagline: "A small but growing sport in India, with sharp hand-eye demands",
  },
  {
    id: "softball",
    name: "Softball",
    category: "field",
    individual: 2, explosive: 4, endurance: 3, visualTracking: 5, reactFast: 4,
    sustainedFocus: 3, pressureTolerance: 3, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 5, agilityNeed: 3, minWeeklyHours: 5,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "moderate", ageWindowIdeal: [7, 14], ageWindowCutoff: 17,
    specializationIntensity: "high",
    costRange: "₹1,500 – 4,000/month",
    tagline: "A growing girls'-friendly team sport with sharp hand-eye demands",
  },
  {
    id: "ultimate-frisbee",
    name: "Ultimate Frisbee",
    category: "field",
    individual: 1, explosive: 4, endurance: 5, visualTracking: 4, reactFast: 4,
    sustainedFocus: 2, pressureTolerance: 2, repetitionNeed: 3, contactRequired: 1,
    visionDemand: 3, agilityNeed: 4, minWeeklyHours: 5,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 2,
    ageStartSensitivity: "flexible", ageWindowIdeal: [8, 15], ageWindowCutoff: 18,
    specializationIntensity: "low",
    costRange: "₹500 – 2,000/month",
    tagline: "A growing self-officiated team sport built around fair play",
  },
  {
    id: "ten-pin-bowling",
    name: "Ten-pin Bowling",
    category: "precision",
    individual: 4, explosive: 2, endurance: 2, visualTracking: 3, reactFast: 2,
    sustainedFocus: 4, pressureTolerance: 4, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 3, agilityNeed: 2, minWeeklyHours: 3,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "3k-7k", minCityTier: 1,
    ageStartSensitivity: "flexible", ageWindowIdeal: [8, 16], ageWindowCutoff: 99,
    specializationIntensity: "high",
    costRange: "₹3,000 – 7,000/month",
    tagline: "A precision sport with a real competitive circuit, mostly in metro cities",
  },
  {
    id: "yoga",
    name: "Yoga",
    category: "gymnastics",
    individual: 5, explosive: 2, endurance: 3, visualTracking: 1, reactFast: 1,
    sustainedFocus: 5, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 1, agilityNeed: 5, minWeeklyHours: 5,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "indoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 3,
    ageStartSensitivity: "moderate", ageWindowIdeal: [6, 14], ageWindowCutoff: 18,
    specializationIntensity: "low",
    costRange: "₹500 – 2,000/month",
    tagline: "A flexibility-and-balance discipline with growing school-level competitions",
  },
  {
    id: "surfing",
    name: "Surfing",
    category: "water",
    individual: 5, explosive: 4, endurance: 4, visualTracking: 3, reactFast: 4,
    sustainedFocus: 3, pressureTolerance: 3, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 2, agilityNeed: 4, minWeeklyHours: 6,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: true, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 1,
    ageStartSensitivity: "moderate", ageWindowIdeal: [8, 15], ageWindowCutoff: 20,
    specializationIntensity: "high",
    costRange: "₹6,000 – 14,000/month",
    tagline: "An emerging coastal sport, geography-limited but genuinely growing",
  },
  {
    id: "marathon-running",
    name: "Marathon/Distance Running",
    category: "athletics",
    individual: 5, explosive: 1, endurance: 5, visualTracking: 1, reactFast: 1,
    sustainedFocus: 5, pressureTolerance: 4, repetitionNeed: 5, contactRequired: 1,
    visionDemand: 1, agilityNeed: 1, minWeeklyHours: 6,
    buildPreference: "lean", heightAdvantage: "any", environmentPreference: "outdoor",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "under-3k", minCityTier: 3,
    ageStartSensitivity: "flexible", ageWindowIdeal: [10, 16], ageWindowCutoff: 20,
    specializationIntensity: "low",
    costRange: "₹500 – 2,500/month",
    tagline: "A pure-endurance discipline riding India's booming running-club culture",
  },
  {
    id: "padel",
    name: "Padel",
    category: "racket",
    individual: 2, explosive: 4, endurance: 3, visualTracking: 5, reactFast: 5,
    sustainedFocus: 3, pressureTolerance: 4, repetitionNeed: 4, contactRequired: 1,
    visionDemand: 4, agilityNeed: 4, minWeeklyHours: 5,
    buildPreference: "any", heightAdvantage: "any", environmentPreference: "either",
    requiresWater: false, requiresContact: false,
    minBudgetTier: "7k-15k", minCityTier: 1,
    ageStartSensitivity: "flexible", ageWindowIdeal: [8, 14], ageWindowCutoff: 18,
    specializationIntensity: "high",
    costRange: "₹8,000 – 18,000/month",
    tagline: "India's fastest-growing new racquet sport, exploding in metro cities since 2023",
  },
];

export const PRIOR_SPORTS_OPTIONS = [
  "Badminton", "Tennis", "Cricket", "Football", "Swimming",
  "Gymnastics", "Chess", "Table Tennis", "Basketball", "Kabaddi",
  "Wrestling", "Shooting", "Athletics", "Volleyball", "Hockey",
  "Boxing", "Cycling", "Skating", "Kho-Kho", "Mallakhamb", "Judo",
  "Taekwondo", "Karate", "Fencing", "Archery", "Weightlifting",
  "Powerlifting", "Squash", "Handball", "Netball", "Rugby",
  "Water Polo", "Diving", "Rowing", "Sailing", "Golf", "Equestrian",
  "Skateboarding", "Sport Climbing", "Triathlon", "Snooker/Billiards",
  "Carrom", "Baseball", "Softball", "Ultimate Frisbee", "Ten-pin Bowling",
  "Yoga", "Surfing", "Marathon/Distance Running", "Padel",
];
