"use client";

import {
    SportPathway,
} from "@/modules/sports/services/pathway";
import { motion } from "framer-motion";
import {
    Check,
    CheckCircle2,
    Copy,
} from "lucide-react";
import { useState } from "react";

import {
    COACHING_FEE_TIERS,
    pathwayLevels
} from '../config/constants';

// ─── P4: Budget Calculator ────────────────────────────────────────────────────

export function BudgetCalculator({ pathway }: { pathway: SportPathway }) {
  const [selectedLevels, setSelectedLevels] = useState<number[]>([
    1, 2, 3, 4, 5,
  ]);
  const [copied, setCopied] = useState(false);

  const toggleLevel = (lvl: number) => {
    setSelectedLevels((prev) =>
      prev.includes(lvl)
        ? prev.filter((l) => l !== lvl)
        : [...prev, lvl].sort(),
    );
  };

  // Parse a cost string like "₹2,000 – ₹5,000" → midpoint
  const parseCostMid = (cost: string): number => {
    const nums = cost.replace(/[₹,\s]/g, "").match(/\d+/g);
    if (!nums || nums.length === 0) return 0;
    if (nums.length >= 2)
      return (Number(nums[0]) + Number(nums[nums.length - 1])) / 2;
    return Number(nums[0]);
  };

  const levelData = pathway.levels.filter((l) =>
    selectedLevels.includes(l.level),
  );

  type RowData = {
    level: number;
    label: string;
    equipment: string;
    equipmentMid: number;
    coaching: string;
    coachingMid: number;
    travel: string;
    financial: string;
  };

  const rows: RowData[] = levelData.map((lv) => {
    const equip =
      pathway.equipment?.find((e) =>
        e.level.toLowerCase().includes(lv.label.toLowerCase()),
      ) || pathway.equipment?.[lv.level - 1];
    const fees = COACHING_FEE_TIERS[lv.level];
    const commitment = pathwayLevels.find((l) => l.level === lv.level)
      ?.parentalCommitment || {
      time: "Varies",
      financial: "Varies",
      travel: "Varies",
      role: "Supportive Parent",
    };
    return {
      level: lv.level,
      label: lv.label,
      equipment: equip?.estimatedCost || "Varies",
      equipmentMid: equip ? parseCostMid(equip.estimatedCost) : 0,
      coaching: fees.label,
      coachingMid: (fees.low + fees.high) / 2,
      travel: commitment.travel,
      financial: commitment.financial,
    };
  });

  const totalEquip = rows.reduce((s, r) => s + r.equipmentMid, 0);
  // Coaching: annual midpoint per level (assume 10 months active)
  const totalCoaching = rows.reduce((s, r) => s + r.coachingMid * 10, 0);
  const grandTotal = totalEquip + totalCoaching;

  const fmt = (n: number) =>
    n > 0 ? `₹${Math.round(n).toLocaleString("en-IN")}` : "Varies";

  const handleExport = async () => {
    const lines: string[] = [
      `Cost-of-the-Journey Estimate — ${pathway.sportName}`,
      `Generated by PowerMySport on ${new Date().toLocaleDateString("en-IN")}`,
      "",
      "Level-by-Level Breakdown:",
      "─".repeat(50),
    ];
    rows.forEach((r) => {
      lines.push(`\n[Level ${r.level}] ${r.label}`);
      lines.push(`  Equipment : ${r.equipment}`);
      lines.push(`  Coaching  : ${r.coaching} (est. 10 active months)`);
      lines.push(`  Travel    : ${r.travel}`);
    });
    lines.push("");
    lines.push("─".repeat(50));
    lines.push(`Equipment Total  : ${fmt(totalEquip)}`);
    lines.push(`Coaching Total   : ${fmt(totalCoaching)} (10 months/level)`);
    lines.push(`GRAND ESTIMATE   : ${fmt(grandTotal)}`);
    lines.push("");
    lines.push(
      "Note: All figures are indicative estimates. Actual costs vary by location, academy, and individual progression.",
    );

    try {
      await navigator.clipboard.writeText(lines.join("\n"));
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    } catch {}
  };

  return (
    <motion.div
      key="budget"
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{ duration: 0.2 }}
      className="space-y-5"
    >
      {/* Summary numbers — the only thing a parent needs to see first */}
      <div className="grid grid-cols-3 gap-px rounded-2xl overflow-hidden border border-slate-200 bg-slate-100">
        <div className="bg-white px-5 py-5">
          <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-2">
            Equipment
          </p>
          <p className="text-2xl font-extrabold text-slate-900 tabular-nums leading-none">
            {fmt(totalEquip)}
          </p>
        </div>
        <div className="bg-white px-5 py-5">
          <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-2">
            Coaching
          </p>
          <p className="text-2xl font-extrabold text-slate-900 tabular-nums leading-none">
            {fmt(totalCoaching)}
          </p>
          <p className="text-[10px] text-slate-400 mt-1.5">10 months / level</p>
        </div>
        <div className="bg-white px-5 py-5">
          <p className="text-[10px] font-bold uppercase tracking-widest text-power-orange mb-2">
            Grand Estimate
          </p>
          <p className="text-2xl font-extrabold text-power-orange tabular-nums leading-none">
            {fmt(grandTotal)}
          </p>
        </div>
      </div>

      {/* Level filters + export */}
      <div className="flex flex-wrap items-center gap-2">
        {pathway.levels.map((lv) => {
          const active = selectedLevels.includes(lv.level);
          return (
            <button
              key={lv.level}
              onClick={() => toggleLevel(lv.level)}
              className={`flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-semibold transition-all ${
                active
                  ? "border-slate-900 bg-slate-900 text-white"
                  : "border-slate-200 bg-white text-slate-500 hover:border-slate-400"
              }`}
            >
              {active && <CheckCircle2 className="h-3 w-3" />}
              {lv.label}
            </button>
          );
        })}
        <button
          onClick={handleExport}
          className="ml-auto flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold text-slate-500 hover:border-slate-400 transition"
        >
          {copied ? (
            <>
              <Check className="h-3 w-3 text-power-orange" /> Copied!
            </>
          ) : (
            <>
              <Copy className="h-3 w-3" /> Export
            </>
          )}
        </button>
      </div>

      {/* Level breakdown — clean table rows */}
      {rows.length > 0 && (
        <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden">
          {/* Header row */}
          <div className="grid grid-cols-4 gap-4 border-b border-slate-100 px-5 py-2 bg-slate-50">
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">
              Level
            </p>
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">
              Equipment
            </p>
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">
              Coaching / mo
            </p>
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">
              Travel
            </p>
          </div>
          {rows.map((row, idx) => (
            <div
              key={row.level}
              className={`grid grid-cols-4 gap-4 px-5 py-3 items-center ${idx < rows.length - 1 ? "border-b border-slate-100" : ""}`}
            >
              <div className="flex items-center gap-2.5 min-w-0">
                <span className="shrink-0 flex h-5 w-5 items-center justify-center rounded-full border border-slate-300 text-[10px] font-extrabold text-slate-600">
                  {row.level}
                </span>
                <span className="text-sm font-semibold text-slate-800 truncate">
                  {row.label}
                </span>
              </div>
              <p className="text-sm font-semibold text-slate-800 tabular-nums">
                {row.equipment}
              </p>
              <p className="text-sm font-semibold text-slate-800">
                {row.coaching}
              </p>
              <p className="text-sm text-slate-500 leading-snug truncate">
                {row.travel}
              </p>
            </div>
          ))}
        </div>
      )}

      {/* Disclaimer */}
      <p className="text-xs text-slate-400 leading-relaxed">
        Indicative estimates only. Actual costs vary by city, academy, and
        progression speed. Coaching ranges are generic across sports —
        specialist academies may differ.
      </p>
    </motion.div>
  );
}

