import mongoose, { Document, Schema } from "mongoose";

export interface FederationInfo {
  name: string;
  acronym: string;
  website?: string;
  type: "govt" | "private" | "hybrid";
  about?: string;
}

/**
 * Canonical tournament record.
 * Curated tournaments (isCurated=true) are hand-seeded and shown on detail pages.
 * Scraped tournaments (isCurated=false) are generated by RealDataScraperService.
 */
export interface TournamentDocument extends Document {
  sportSlug: string;
  city?: string;
  name: string;
  level: string;
  description: string;
  ageGroup: string;
  prerequisiteId?: string;
  prerequisiteName?: string;
  prerequisiteGuide?: string[];
  documentChecklist?: string[];
  /** Real URLs returned by Google Search grounding — shown to parents as proof */
  sourceUrls: string[];
  /** e.g. "Usually held in January–February" — typical annual window */
  typicalDates?: string;
  /** e.g. "Registration closes 3 weeks before the event" */
  registrationDeadline?: string;
  /** false until an admin/moderator has eyeballed it */
  isVerified: boolean;
  lastScrapedAt: Date;

  // ── Curated-only fields ────────────────────────────────────────────────────
  /** URL-safe slug for the detail page route, e.g. "ipl", "ranji-trophy" */
  slug?: string;
  /** Hand-curated entry — these are always shown, never auto-replaced by the scraper */
  isCurated: boolean;
  /** The governing body that organises this tournament */
  federation?: FederationInfo;
  /** Numbered steps telling a parent/player how to participate */
  participationGuide?: string[];
  /** How players qualify — ranking, state selection, open registration, etc. */
  qualificationPath?: string;
  /** Round-robin, knockout, league, swiss, etc. */
  format?: string;
  /** Flagship = the defining event of the sport; ranking = points-earning; developmental = youth/grassroots */
  prestige?: "flagship" | "ranking" | "developmental";
  /** Prize money or prestige reward, e.g. "₹10 Cr total purse" or "World ranking points" */
  prizePool?: string;
  /** Optional direct registration or official website link */
  registrationUrl?: string;
  /** Typical cost for a player/family to enter — e.g. "₹500 trial fee + no entry fee for selected players" */
  entryFee?: string;
  /** Specific criteria used to select players — e.g. "State quota via annual trials in September" */
  selectionCriteria?: string;
  /** Detailed awards — cash, trophies, medals, ranking points, match fees */
  prizes?: string;
  /** 4–6 quick verifiable facts about the tournament — scale, history, numbers */
  keyFacts?: string[];
  /** Critical must-know notes for parents — ID rules, residency, cutoff gotchas */
  importantNotes?: string[];
  /** Full ranking circuit / tier system for this sport — explains the ladder this tournament sits on */
  circuitContext?: string;

  createdAt: Date;
  updatedAt: Date;
}

const federationSchema = new Schema<FederationInfo>(
  {
    name: { type: String, required: true },
    acronym: { type: String, required: true },
    website: { type: String },
    type: { type: String, enum: ["govt", "private", "hybrid"], required: true },
    about: { type: String },
  },
  { _id: false },
);

const tournamentSchema = new Schema<TournamentDocument>(
  {
    sportSlug: { type: String, required: true, lowercase: true, index: true },
    city: { type: String, index: true },
    name: { type: String, required: true, trim: true },
    level: { type: String, required: true },
    description: { type: String, required: true },
    ageGroup: { type: String, required: true },
    prerequisiteId: { type: String },
    prerequisiteName: { type: String },
    prerequisiteGuide: [{ type: String }],
    documentChecklist: [{ type: String }],
    typicalDates: { type: String },
    registrationDeadline: { type: String },
    sourceUrls: { type: [String], default: [] },
    isVerified: { type: Boolean, default: false },
    lastScrapedAt: { type: Date, default: Date.now },

    slug: { type: String, lowercase: true, trim: true, sparse: true },
    isCurated: { type: Boolean, default: false, index: true },
    federation: { type: federationSchema },
    participationGuide: [{ type: String }],
    qualificationPath: { type: String },
    format: { type: String },
    prestige: {
      type: String,
      enum: ["flagship", "ranking", "developmental"],
    },
    prizePool: { type: String },
    registrationUrl: { type: String },
    entryFee: { type: String },
    selectionCriteria: { type: String },
    prizes: { type: String },
    keyFacts: [{ type: String }],
    importantNotes: [{ type: String }],
    circuitContext: { type: String },
  },
  { timestamps: true },
);

tournamentSchema.index({ sportSlug: 1, name: 1 }, { unique: true });
tournamentSchema.index({ slug: 1 }, { unique: true, sparse: true });
tournamentSchema.index({ isCurated: 1, sportSlug: 1 });

export const Tournament =
  mongoose.models.Tournament ||
  mongoose.model<TournamentDocument>("Tournament", tournamentSchema);
